sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_NAME: sarathsnair
  - GIT_EMAIL: sarathsnairxyz@gmail.com
  - SOURCE_DIR: "build"
  - DEPLOY_BRANCH: source
  - TARGET_BRANCH: master
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
after_success:
    - echo "sarathsnair.me" > ./build/CNAME
    - ./scripts/deploy.sh