name: Github pages Build and Deploy
on:
  push:
    branches:
      - "source"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["15.x"]

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.5.1

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install -g grunt-cli
          npm install
          grunt build-prod

      - name: Updating CNAME file
        run: |
          echo "sarathsnair.me" > ./build/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: master # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
